export { default as Hero } from './Hero'
export { default as ScrollSections } from './ScrollSections'
export { default as Pricing } from './Pricing'
export { default as Modules } from './Modules'
export { default as Features } from './Services'
export { default as About } from './About'
export { default as Contact } from './Contact'
